name: Backend CI
on:
  push:

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [15, 16]
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2.3.5
      - name: Use Node.js
        uses: actions/setup-node@v2.4.1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: |
          npm -v
          npm init --yes
          npm init -w pkg-a --yes
          npm install react-scripts -w pkg-a
          npm install @storybook/react -D -w pkg-a
          npm ls
